# Generated by Django 5.1.1 on 2024-10-20 01:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=99, verbose_name='Nombre')),
                ('biografia', models.TextField(verbose_name='Biografía')),
                ('fnacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(max_length=99, verbose_name='Nacionalidad')),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'editorial',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=99, verbose_name='Nombre')),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=99, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=99, unique=True, verbose_name='Correo')),
                ('password', models.CharField(max_length=99, verbose_name='Contraseña')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=99, verbose_name='Título')),
                ('fpublicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('id_editorial', models.IntegerField(verbose_name='ID Editorial')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('nro_paginas', models.IntegerField(verbose_name='Número de Páginas')),
                ('idioma', models.IntegerField(verbose_name='Idioma')),
                ('estado', models.IntegerField(default=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbiblioteca.autor', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libros',
            },
        ),
    ]
